from optparse import make_option
from django.core.management.base import BaseCommand, CommandError
from rotationSchedule_app.models import Block, Resident, Year, Track, Program, Rotation, Event, Schedule, Template, TemplateEvent, RotationSet, YearSet
import copy
import random
import operator
import sys
import logging
import os
from django.conf import settings
import datetime
from dateutil.rrule import rrule, WEEKLY

logging.basicConfig(stream=sys.stdout, format='%(message)s',level=logging.INFO)

class Command(BaseCommand):
	args = '<event_pk event_start event_end>'
	option_list = BaseCommand.option_list + (
    	make_option('--long', '-l', dest='long',
    		help='Help for the long options'),
    	)
	help = 'Help text goes here'
	
	def handle(self, *args, **options):
		os.chdir(os.path.join(os.path.dirname(os.path.abspath(settings.BASE_DIR)), 'rotationSchedule_app/management/commands'))		

		#os.system('pyomo --instance-only --save-model=rotsched.lp XYZ_test.py XYZ_test.dat --symbolic-solver-labels')
		os.system('pyomo --instance-only --save-model=rotsched.lp rotation_schedulerXYZ_debug.py XYZ_test2.dat --symbolic-solver-labels')

		import cplex
		cpx = cplex.Cplex("rotsched.lp") ### any lp file generated by pyomo
		M = 3 #numSolns to generate
		ObjTolerance = 0.80 #fraction of best objective tolerated while finding multiple schedules,1 == find only optimal
		cpx.solve() # solve for optimal solution
		print cpx.solution.get_objective_value()
		successful = cpx.solution.get_status()
		print(successful)
		#### successful != 101 := problem is infeasible .. Raise flags for the web app


		if successful == 101: #101 is code for MIP_optimal #Todo: remove this hardcode
			print "success!!"
			bestObjective = cpx.solution.get_objective_value()


			for res in range(1,5):
				for rotation in range(1,6):
					for week in range(1,9):
						for cohort in range(1,3):
							if str(cpx.solution.pool.get_values(0,"Zc("+str(res)+"_"+str(rotation)+"_"+str(week)+"_"+str(cohort)+")")) == "1.0":
								print str("Zc("+str(res)+"_"+str(rotation)+"_"+str(week)+"_"+str(cohort)+")")

			for res in range(1,5):
				for cohort in range(1,3):
					if str(cpx.solution.pool.get_values(0,"K("+str(res)+"_"+str(cohort)+")")) == "1.0":
						print str("K("+str(res)+"_"+str(cohort)+")")



# set R := 1 2 3 4 5;
# set Redu := 1 2 3 4; 
# set Ycov := 1 2 3 4 5;
# set E:= 1 2 3;
# set W := 1 2 3 4 5 6 7 8;
# set D := 1 2 3 4;
# set Y := 1 2 3;
# set B := 1 2;
# set C := 1 2;
# set Couples := 1 2; 










